version: "3"

services:
  mysql:
    container_name: mysql
    image: psyoblade/data-engineer-intermediate-day1-mysql:1.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: sqoop
      MYSQL_PASSWORD: sqoop
    ports:
      - '3306:3306'
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 3s
      timeout: 1s
      retries: 3
    volumes:
      - ./mysql/etc:/etc/mysql/conf.d
  sqoop:
    container_name: sqoop
    image: psyoblade/data-engineer-intermediate-day1-sqoop:1.0
    tty: true
    environment:
      LANG: ko_KR.UTF-8
    ports:
      - '8088:8088'
      - '10020:10020'
      - '19888:19888'
      - '60070:50070'
      - '60075:50075'
    networks:
      - default
    depends_on:
      - mysql
    volumes:
      - ./sqoop/jars:/jdbc
      - ./tmp/target:/tmp/target
  fluentd:
    container_name: fluentd
    image: psyoblade/data-engineer-basic-fluentd:1.1
    user: root
    tty: true
    ports:
      - 9880:9880
    volumes:
      - ./tmp/source:/tmp/source
      - ./tmp/target:/tmp/target
networks:
  default:
    name: default_network
